CREATE DATABASE IF NOT EXISTS AWSETL;
CREATE SCHEMA IF NOT EXISTS AWSETL.AWSETL;

USE DATABASE AWSETL;
USE SCHEMA AWSETL;

CREATE OR REPLACE STORAGE INTEGRATION aws_s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::859190601457:role/snowflakerole'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3://aws-etl-bucket-ap/');

DESC INTEGRATION aws_s3_integration;

CREATE OR REPLACE FILE FORMAT awsetl_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE aws_s3_stage
  STORAGE_INTEGRATION = aws_s3_integration
  URL = 's3://aws-etl-bucket-ap/'
  FILE_FORMAT = awsetl_csv_format;

LIST @aws_s3_stage;

CREATE OR REPLACE TABLE AIR_CONDITIONERS (
  NAME TEXT,
  MAIN_CATEGORY TEXT,
  SUB_CATEGORY TEXT,
  IMAGE TEXT,
  LINK TEXT,
  RATINGS TEXT,
  NO_OF_RATINGS TEXT,
  DISCOUNT_PRICE TEXT,
  ACTUAL_PRICE TEXT
);

COPY INTO AIR_CONDITIONERS FROM @aws_s3_stage/Air_Conditioners.csv FILE_FORMAT = 'awsetl_csv_format';

ALTER TABLE AIR_CONDITIONERS ADD COLUMN DISCOUNT_PRICE_CLEAN NUMBER;
ALTER TABLE AIR_CONDITIONERS ADD COLUMN ACTUAL_PRICE_CLEAN NUMBER;

UPDATE AIR_CONDITIONERS SET
  DISCOUNT_PRICE_CLEAN = TRY_TO_NUMBER(REPLACE(REPLACE(DISCOUNT_PRICE, '₹', ''), ',', '')),
  ACTUAL_PRICE_CLEAN = TRY_TO_NUMBER(REPLACE(REPLACE(ACTUAL_PRICE, '₹', ''), ',', ''));
ALTER TABLE AIR_CONDITIONERS DROP COLUMN DISCOUNT_PRICE, ACTUAL_PRICE;
ALTER TABLE AIR_CONDITIONERS DROP COLUMN LINK;
ALTER TABLE AIR_CONDITIONERS DROP COLUMN IMAGE;
SELECT * FROM AIR_CONDITIONERS LIMIT 5;
